services:
  frontend:
    env_file: ./.env
    container_name: budget.tns-client
    build:
      context: ./client
      dockerfile: Dockerfile
    # The 'environment' block is removed as build-time env vars (like REACT_APP_*)
    # should be handled inside the Dockerfile build process if needed, using build args.
    # The PORT env var is not needed by the Nginx container.
    ports:
      # Map the host port (defined by CLIENT_PORT in your .env file) to port 80 inside the container (where Nginx listens).
      - ${CLIENT_PORT}:80
    networks:
      Web-Budget-App:
        aliases:
          - frontend
    # VOLUMES REMOVED for the frontend service.
    # For production, we want to use the static files that were copied into the image
    # during the `docker build` process. Mounting volumes here would overwrite the built files.
    depends_on:
      - backend
  backend:
    env_file: ./.env
    container_name: budget.tns-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      Web-Budget-App:
        aliases:
          - backend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

networks:
  Web-Budget-App:
    external: true
