services:
  # Backend Service (Node.js API)
  backend:
    # MODIFIED: Replaced 'build' with 'image'
    image: tns-budget-backend:latest
    environment:
      - PORT=5000 # Set the internal port for the backend
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  # Frontend Service (React App served by Nginx)
  frontend:
    # MODIFIED: Replaced 'build' with 'image'
    image: tns-budget-frontend:latest
    depends_on:
      - backend
    ports:
      # This maps the host port 3000 to the container port 3000
      - "3000:3000"
    deploy:
      replicas: 2 # Running 2 replicas for high availability
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
