version: "3"
services:
  frontend:
    container_name: react-budget-app-mongo-client
    build:
        context: ./client
        dockerfile: Dockerfile
    # image: vikasraj/awesome_web
    ports:
        - "3001:3000"
    volumes:
        - ./client:/usr/src/app
  backend:
    container_name: react-budget-app-mongo-server
    build:
        context: ./server
        dockerfile: Dockerfile
    # image: vikasraj/awesome_server
    ports:
        - "5001:5000"
    volumes:
        - ./server:/usr/src/app
