services:
  backend:
    build: ./server
    restart: unless-stopped
    ports:
      - "5001:5000" # Expose backend on port 5001 for Nginx Proxy Manager
    env_file: .env # Load all variables from the .env file

  frontend:
    build:
      context: ./client
      args:
        # Pass variables from .env to the frontend build
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_WS_URL: ${REACT_APP_WS_URL}
        REACT_APP_VERSION: ${REACT_APP_VERSION}
    restart: unless-stopped
    ports:
      - "3000:3000" # Expose frontend on port 3000
    depends_on:
      - backend
