# This simplified file is for a single-node deployment.
services:
  backend:
    build: ./server
    image: tns-budget-backend:latest # Build and tag the image
    restart: unless-stopped
    ports:
      - "5001:5000" # Expose backend on port 5001
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    secrets:
      - mongo_user
      - mongo_pass
      - jwt_secret

  frontend:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_WS_URL=${REACT_APP_WS_URL}
        - REACT_APP_VERSION=${REACT_APP_VERSION}
    image: tns-budget-frontend:latest # Build and tag the image
    restart: unless-stopped
    ports:
      - "3000:3000" # Expose frontend on port 3000
    depends_on:
      - backend

secrets:
  mongo_user:
    file: ./mongo_user.txt
  mongo_pass:
    file: ./mongo_pass.txt
  jwt_secret:
    file: ./jwt_secret.txt
