services:
  frontend:
    env_file: ./.env
    container_name: budget.tns-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      # MODIFIED: The internal container port is now 3000 to match our Nginx config.
      # The host port is still CLIENT_PORT (3000), so the mapping is now 3000:3000.
      - ${CLIENT_PORT}:3000
    networks:
      Web-Budget-App:
        aliases:
          - frontend
    depends_on:
      - backend
  backend:
    env_file: ./.env
    container_name: budget.tns-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      Web-Budget-App:
        aliases:
          - backend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

networks:
  Web-Budget-App:
    external: true
