services:
  # Backend Service (Node.js API)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: auth-budgettns-backend
    restart: unless-stopped
    environment:
      - PORT=5000 # Set the internal port for the backend
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  # Frontend Service (React App served by Nginx)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_WS_URL=${REACT_APP_WS_URL}
        - REACT_APP_VERSION=${REACT_APP_VERSION}
    container_name: auth-budgettns-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      # This maps the host port 3000 to the container port 3000
      - "3000:3000"
    deploy:
      replicas: 2 # Running 2 replicas for high availability
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
