services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    deploy:
      placement:
        constraints: [node.role == manager]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/tns-budget-backend
    # MODIFIED: Added a ports section to expose the backend on port 5001
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/tns-budget-frontend
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
