services:
  frontend:
    env_file: ./.env
    container_name: budget.tns-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      # This correctly maps port 3000 on your server to port 80 inside the Nginx container.
      # You will access the site at http://10.10.10.10:3000.
      - ${CLIENT_PORT}:80
    networks:
      Web-Budget-App:
        aliases:
          - frontend
    # Volumes for the frontend are removed. In production, we use the files built *into* the image.
    depends_on:
      - backend
  backend:
    env_file: ./.env
    container_name: budget.tns-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      Web-Budget-App:
        aliases:
          - backend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

networks:
  Web-Budget-App:
    external: true
