services:
  frontend:
    env_file: ./.env
    container_name: budget.tns-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      PORT: ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      Web-Budget-App:
        aliases:
          - frontend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
  backend:
    env_file: ./.env
    container_name: budget.tns-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      Web-Budget-App:
        aliases:
          - backend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

networks:
  Web-Budget-App:
    external: true
