services:
  frontend:
    env_file: ./.env
    container_name: budget.tns-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      # MODIFIED: The internal container port is now 3000 to match our Nginx config.
      # The host port is still CLIENT_PORT (3000), so the mapping is now 3000:3000.
      - ${CLIENT_PORT}:3000
    networks:
      Web-Budget-App:
        aliases:
          - frontend
    depends_on:
      - backend
    deploy:
      replicas: 2 # Run 2 instances of your frontend for high availability
      update_config:
        parallelism: 1 # Update one container at a time
        delay: 10s # Wait 10 seconds between updates
        order: start-first # Start the new container before stopping the old one
  backend:
    env_file: ./.env
    container_name: budget.tns-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      Web-Budget-App:
        aliases:
          - backend
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  Web-Budget-App:
    external: true
